### PR TITLE
add layout field to gallery

### PR DESCRIPTION
**Pull request by bhsiao55**

### CODE REVIEW

**Comment by efjacobson** [comment]
looks good to me, over to you @gdbrown

**Comment by gdbrown** [comment]
@bhsiao55 let's do string field instead of enum.  default or null would be whatever the site wants (like carousel) and then some other value (picklist in cms or config... like canvas/page does) provides other options.

ref https://github.com/triniti/schemas/blob/master/schemas/triniti/canvas/mixin/page/latest.xml#L45
check in cms on how that one is setup

**Review by gdbrown — CHANGES_REQUESTED** [review]
@bhsiao55 no enum, do like https://github.com/triniti/schemas/blob/master/schemas/triniti/canvas/mixin/page/latest.xml#L45

**Comment by bhsiao55** [comment]
@gdbrown using string field now and removed enum.

**Review by gdbrown — APPROVED** [review]

**Pull request merged**
